pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'test'
            }
        }
        stage('deploy') {
            steps {
                sh 'deploy'
            }
        }
    }
}
